var data = JSON.parse(JSON.stringify(modeloPageTimer.oData));



if (checkActiveTasks(data.order)) {
    sap.m.MessageToast.show("There is already a task in progress ! Please complete the task before attaching documents to another order!");
} 

// else if (window.hasOwnProperty("cordova")) {
//     capturePhoto();
//     //onPhotoDataSuccess(iconTrash)
// } 

else {
    console.log("Opening File Input")
    fileElem = document.getElementById("file-input");
    fileElem.click();
}
