if (modeloListSESItems.oData[0].status === "Completed") {
    oDialogSign.open();
    var canvas = document.getElementById('signature-pad');
    signaturePad = new SignaturePad(canvas);
    canvas.style.width = '100%';
    canvas.style.height = '100%';
    canvas.width = canvas.offsetWidth;
    canvas.height = canvas.offsetHeight;
} else {
    sap.m.MessageToast.show("Please save the item first !");
}